export enum TypePage {
  NEWS = "news",
  LATEST_NEWS = "new_news",
  MOST_VIEW_NEWS = "most_view_news",
  HOT_NEWS = "hot_news",
  THOISU = "thoi_su",
  PERSPECTIVE = "perspective",
  WORLD = "world",
  BUSINESS = "business",
  START_UP = "start_up",
  ENTERTAINMENT = "entertainment",
  SPORT = "sport",
  TOURISM = "tourism",
  LIFE = "life",
  SCIENCE = "science",
  EDUCATION = "education",
  CONFIDE = "confide",
}
