name: Next.js CI/CD

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm i
      
    - name: Run lint
      run: npm run lint
      
    - name: Build
      run: npm run build
      
    - name: Deploy to production
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      # Thêm các bước triển khai tại đây, ví dụ sử dụng Vercel hoặc server riêng
