name: Next.js CI/CD

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm i

    - name: Run lint
      run: npm run lint

    - name: Build
      run: npm run build

    - name: Deploy to production
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: echo "Add deployment steps here"
      # Example: 
      # uses: vercel/actions/deploy@v1
      # with:
      #   vercel-token: ${{ secrets.VERCEL_TOKEN }}
      #   vercel-org-id: ${{ secrets.ORG_ID }}
      #   vercel-project-id: ${{ secrets.PROJECT_ID }}
